from pathlib import Path

exp_name = Path(__file__).stem

hparams = {
    'file_name':
        f'runs_{exp_name}.txt',
    'entry': 'batch_run_ppo.py',
    'args': [
        {
            'env': '4x3',
            'double_critic': True,
            'lr': 0.00025,
            'lambda0': 0.9,
            'lambda1': 0.7,
            'alpha': 1.,
            'ld_weight': 0.5,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'cheese.95',
            'double_critic': True,
            'lr': 0.0025,
            'lambda0': 0.5,
            'lambda1': 0.9,
            'alpha': 1.,
            'ld_weight': 0.125,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'hallway',
            'double_critic': True,
            'lr': 0.0025,
            'lambda0': 0.7,
            'lambda1': 0.95,
            'alpha': 1.,
            'ld_weight': 0.125,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'heavenhell',
            'double_critic': True,
            'lr': 0.0025,
            'lambda0': 0.95,
            'lambda1': 0.7,
            'alpha': 1.,
            'ld_weight': 0.5,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'network',
            'double_critic': True,
            'lr': 0.0025,
            'lambda0': 0.95,
            'lambda1': 0.1,
            'alpha': 1.,
            'ld_weight': 0.,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'paint',
            'double_critic': True,
            'lr': 0.00025,
            'lambda0': 0.95,
            'lambda1': 0.9,
            'alpha': 1.,
            'ld_weight': 0.25,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'shuttle',
            'double_critic': True,
            'lr': 0.0025,
            'lambda0': 0.9,
            'lambda1': 0.5,
            'alpha': 1.,
            'ld_weight': 0.5,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'tiger-alt-start',
            'double_critic': True,
            'lr': 0.0025,
            'lambda0': 0.5,
            'lambda1': 0.7,
            'alpha': 1.,
            'ld_weight': 0.,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
        {
            'env': 'tmaze_5',
            'double_critic': True,
            'lr': 0.0025,
            'lambda0': 0.9,
            'lambda1': 0.5,
            'alpha': 1.,
            'ld_weight': 0.,
            'entropy_coeff': 0.05,
            'hidden_size': 32,
            'total_steps': int(3e6),
            'steps_log_freq': 4,
            'update_log_freq': 10,
            'seed': 2029,
            'n_seeds': 30,
            'platform': 'gpu',
            'study_name': exp_name
        },
    ]
}
